# Generated by Django 3.2.3 on 2021-05-27 02:08

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
