# Generated by Django 3.2.3 on 2021-06-15 10:43

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_sticker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
